// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team649.robot.commands;

import org.usfirst.frc.team649.robot.Robot;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc.team649.robot.Robot;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class  Drive extends Command {
	double distance;
	double tolerance = 0.25;
	
    public Drive(double distance) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	
    	this.distance = distance;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public Drive(double distance, double tolerance) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	
    	this.distance = distance;
    	this.tolerance = tolerance;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	double setpoint = Robot.drivetrain.getPosition() + distance;
    	Robot.drivetrain.setSetpoint(setpoint);
    	Robot.drivetrain.enable();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	double position = Robot.drivetrain.getPosition();
    	double setpoint = Robot.drivetrain.getSetpoint();
    	double error = Math.abs(setpoint - position);
    	
    	SmartDashboard.putNumber("setpoint: ", setpoint);

        return error < tolerance;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetrain.disable();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
